"""alex auto

Revision ID: 221ac3649c13
Revises: d6e2f91a4b22
Create Date: 2026-08-21 18:29:01.731808

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '221ac3649c13'
down_revision: str | None = 'd6e2f91a4b22'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.create_unique_constraint(None, 'organizations', ['name'])
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.create_unique_constraint(None, 'subscription_plans', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription_plans', type_='unique')
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=True)
    op.drop_constraint(None, 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    # ### end Alembic commands ###
