"""alex auto

Revision ID: 3178bd89cc83
Revises: 0005_create_users
Create Date: 2026-08-19 17:27:39.301710

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3178bd89cc83'
down_revision: str | None = '0005_create_users'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('super_admins_email_key'), 'super_admins', type_='unique')
    op.create_index(op.f('ix_super_admins_email'), 'super_admins', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_super_admins_email'), table_name='super_admins')
    op.create_unique_constraint(op.f('super_admins_email_key'), 'super_admins', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
