"""alex auto

Revision ID: 359836bbea28
Revises: d4e5f6a7b8c9
Create Date: 2026-08-24 18:45:19.648739

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '359836bbea28'
down_revision: str | None = 'd4e5f6a7b8c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
